#!/bin/bash

inicio_ns=`date +%s%N`
inicio=`date +%s`
me=`basename "$0"`
EXT='*.tif *.TIF'
 
[[ ! -z "$1" ]] || \
  { echo ' usage: $0 <SOURCE PATH> [<DEST PATH>]'; \
    echo '        default <DEST PATH> is current path';  \
    exit 0; }

SOURCE="$1"
if [ -z "$2" ]
  then DEST="$(pwd)"
  else DEST="$2"
fi

[[ -d "$SOURCE" ]] || { echo " error: $SOURCE no es un directorio"; exit 0; }
[[ -d "$DEST" ]] || { echo "error: $DEST no es un directorio"; exit 0; }
[[ -d "$DEST/.econvert_thumbnails" ]] || \
   mkdir "$DEST"/.econvert_thumbnails || \
   { echo "error: mkdir no pudo crear un directorio temporal en $DEST"; \
     exit 0; }

# inicio
#echo "[$me] source = $SOURCE | dest = $DEST"

echo "[$me] $(date +%Y-%m-%d\ %T)"

#exit 0

cd "$SOURCE"
shopt -s nullglob; 
pFiles=($EXT); 
shopt -u nullglob;

if [ -z $pFiles ] ; then echo "ERROR: no hay archivos para procesar en $SOURCE"; exit 0; fi

echo -n "Econvert"
c=0
for i in ${pFiles[@]}
do 
   let c=c+1 
   tname=$(basename "${i// /_}" .tif)
   CMD_ECONVERT='econvert -i "$i" --thumbnail 0.0833 -o "$DEST/.econvert_thumbnails/$tname.jpg"'
   #echo "ejecutando:" $(eval "echo $CMD_ECONVERT")
   echo -n "."
   eval $CMD_ECONVERT
done
echo -n "done"
echo " - $c images"

setlabel="-set label '%f'" # problemas con comillas
montageFiles=("$DEST"/.econvert_thumbnails/*.jpg)
if [ -z $montageFiles ] ; then echo "ERROR: no hay archivos .jpg para procesar en $DEST/.econvert_thumbnails/"; exit 0; fi
CMD_MONTAGE='montage "${montageFiles[@]}" -tile 5x -geometry +2+2  -gravity east -pointsize 9 $setlabel -background lightblue "$DEST"/tile.jpg'
# echo "ejecutando:" $(eval "echo $CMD_MONTAGE")
echo -n "Montage"
eval $CMD_MONTAGE && { echo -n "."; echo "done";}
   
# rm $DEST/.econvert_thumbnails/*.tif
# rmdir $DEST/.econvert_thumbnails

fin_ns=`date +%s%N`
fin=`date +%s`

let total_ns=$fin_ns-$inicio_ns
let total=$fin-$inicio

echo "Total time: ${total}s" # [$total_ns nanoseg]"

