#!/bin/bash

inicio_ns=`date +%s%N`
inicio=`date +%s`

[[ ! -z "$1" ]] || \
  { echo ' usage: $0 <SOURCE PATH> [<DEST PATH>]'; \
    echo '        default <DEST PATH> is current path';  \
    exit 0; }

SOURCE="$1"
if [ -z "$2" ]
  then DEST="$(pwd)"
  else DEST="$2"
fi

[[ -d "$SOURCE" ]] || { echo " error: $SOURCE no es un directorio"; exit 0; }
[[ -d "$DEST" ]] || { echo "error: $DEST no es un directorio"; exit 0; }
[[ -d "$DEST/.econvert_thumbnails" ]] || \
   mkdir $DEST/.econvert_thumbnails || \
   { echo "error: mkdir no pudo crear un directorio temporal en $DEST"; \
     exit 0; }

# inicio
echo -e "\n Iniciando $0 \n SOURCE = $SOURCE \n DEST = $DEST \n"

#exit 0

n=0
cd $SOURCE
for i in *tif
do 
   #n=$(( n+1 ))
   CMD_ECONVERT="econvert -i $i --thumbnail 0.0833 -o $DEST/.econvert_thumbnails/`basename $i .tif`.jpg"
   echo "ejecutando: $CMD_ECONVERT"
   echo
   eval $CMD_ECONVERT
done

CMD_MONTAGE="montage $DEST/.econvert_thumbnails/*.jpg -tile 5x -geometry +2+2  -gravity east -pointsize 9 -set label '%f' -background lightblue $DEST/tile.jpg"
   echo "ejecutando: $CMD_MONTAGE"
   eval $CMD_MONTAGE

# rm $DEST/.econvert_thumbnails/*.tif
# rmdir $DEST/.econvert_thumbnails

fin_ns=`date +%s%N`
fin=`date +%s`

let total_ns=$fin_ns-$inicio_ns
let total=$fin-$inicio

echo -e "\n\ntiempo total: ${total}s [$total_ns nanoseg] \n"
