#!/bin/bash

FILE_LIST="$1"
[[ -f "$FILE_LIST" ]] || { echo " error: $FILE_LIST no existe"; exit 0; }

echo "Procesando ${FILE_LIST}..."

process() {

   local sPath="$1"
   echo "$sPath"
   local source="/srv/TesisDigitalizadas/$sPath" #production
   # local source="/srv/jp/source_test/$sPath" #testing
   local work="/srv/OCR/TEST/${sPath// /_}"
   [[ -d "$work" ]] || mkdir "$work";
   fcen-thumbtable "$source" "$work"
   fcen-postprocessing "src=$source" "wrk=$work" default quiet

}

source "$FILE_LIST"

