#!/bin/bash

thispath=$(dirname "$0")

cp -v $thispath/scripts/fcen-thumbtable ~/bin
chmod -v a+x ~/bin/fcen-thumbtable
echo ""

cp $thispath/scripts/fcen-postprocessing ~/bin
chmod -v a+x ~/bin/fcen-postprocessing
echo ""

cp $thispath/scripts/utils/batch_process ~/bin/fcen-batch_process
chmod -v a+x ~/bin/fcen-batch_process
echo ""

cp -rv $thispath/scripts/filters ~/bin/
echo ""

exit 0
